/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as CCompanySlugRouteImport } from './routes/c.$companySlug'
import { Route as AuthenticatedPaymentRouteImport } from './routes/_authenticated.payment'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as CCompanySlugIndexRouteImport } from './routes/c.$companySlug.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as OauthMercadopagoCallbackRouteImport } from './routes/oauth.mercadopago.callback'
import { Route as CCompanySlugVendasRouteImport } from './routes/c.$companySlug.vendas'
import { Route as CCompanySlugSacolaRouteImport } from './routes/c.$companySlug.sacola'
import { Route as CCompanySlugPerfilRouteImport } from './routes/c.$companySlug.perfil'
import { Route as CCompanySlugPagamentoRouteImport } from './routes/c.$companySlug.pagamento'
import { Route as CCompanySlugMeusPedidosRouteImport } from './routes/c.$companySlug.meus-pedidos'
import { Route as CCompanySlugFeedRouteImport } from './routes/c.$companySlug.feed'
import { Route as CCompanySlugDesconexaoRouteImport } from './routes/c.$companySlug.desconexao'
import { Route as CCompanySlugConfirmadoRouteImport } from './routes/c.$companySlug.confirmado'
import { Route as CCompanySlugCheckoutRouteImport } from './routes/c.$companySlug.checkout'
import { Route as AuthenticatedAppProdutosRouteImport } from './routes/_authenticated.app.produtos'
import { Route as AuthenticatedAppPersonaRouteImport } from './routes/_authenticated.app.persona'
import { Route as AuthenticatedAppPedidosRouteImport } from './routes/_authenticated.app.pedidos'
import { Route as AuthenticatedAppInteligenciaRouteImport } from './routes/_authenticated.app.inteligencia'
import { Route as AuthenticatedAppFinanceiroRouteImport } from './routes/_authenticated.app.financeiro'
import { Route as AuthenticatedAppFeedRouteImport } from './routes/_authenticated.app.feed'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated.app.configuracoes'
import { Route as AuthenticatedAppClientesRouteImport } from './routes/_authenticated.app.clientes'
import { Route as AuthenticatedAppCatalogoRouteImport } from './routes/_authenticated.app.catalogo'
import { Route as AuthenticatedAppAtendimentoRouteImport } from './routes/_authenticated.app.atendimento'
import { Route as AuthenticatedAdminMetricasRouteImport } from './routes/_authenticated.admin.metricas'
import { Route as AuthenticatedAdminLicencasRouteImport } from './routes/_authenticated.admin.licencas'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated.admin.financeiro'
import { Route as AuthenticatedAdminEmpresasRouteImport } from './routes/_authenticated.admin.empresas'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated.admin.configuracoes'
import { Route as AuthenticatedAdminAprovacoesRouteImport } from './routes/_authenticated.admin.aprovacoes'
import { Route as CCompanySlugMTableSlugRouteImport } from './routes/c.$companySlug.m.$tableSlug'
import { Route as AuthenticatedAdminEmpresasIdRouteImport } from './routes/_authenticated.admin.empresas.$id'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CCompanySlugRoute = CCompanySlugRouteImport.update({
  id: '/c/$companySlug',
  path: '/c/$companySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPaymentRoute = AuthenticatedPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CCompanySlugIndexRoute = CCompanySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const OauthMercadopagoCallbackRoute =
  OauthMercadopagoCallbackRouteImport.update({
    id: '/oauth/mercadopago/callback',
    path: '/oauth/mercadopago/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const CCompanySlugVendasRoute = CCompanySlugVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const CCompanySlugSacolaRoute = CCompanySlugSacolaRouteImport.update({
  id: '/sacola',
  path: '/sacola',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const CCompanySlugPerfilRoute = CCompanySlugPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const CCompanySlugPagamentoRoute = CCompanySlugPagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const CCompanySlugMeusPedidosRoute = CCompanySlugMeusPedidosRouteImport.update({
  id: '/meus-pedidos',
  path: '/meus-pedidos',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const CCompanySlugFeedRoute = CCompanySlugFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const CCompanySlugDesconexaoRoute = CCompanySlugDesconexaoRouteImport.update({
  id: '/desconexao',
  path: '/desconexao',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const CCompanySlugConfirmadoRoute = CCompanySlugConfirmadoRouteImport.update({
  id: '/confirmado',
  path: '/confirmado',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const CCompanySlugCheckoutRoute = CCompanySlugCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const AuthenticatedAppProdutosRoute =
  AuthenticatedAppProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPersonaRoute = AuthenticatedAppPersonaRouteImport.update({
  id: '/persona',
  path: '/persona',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPedidosRoute = AuthenticatedAppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppInteligenciaRoute =
  AuthenticatedAppInteligenciaRouteImport.update({
    id: '/inteligencia',
    path: '/inteligencia',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFinanceiroRoute =
  AuthenticatedAppFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFeedRoute = AuthenticatedAppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClientesRoute =
  AuthenticatedAppClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCatalogoRoute =
  AuthenticatedAppCatalogoRouteImport.update({
    id: '/catalogo',
    path: '/catalogo',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAtendimentoRoute =
  AuthenticatedAppAtendimentoRouteImport.update({
    id: '/atendimento',
    path: '/atendimento',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminMetricasRoute =
  AuthenticatedAdminMetricasRouteImport.update({
    id: '/metricas',
    path: '/metricas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLicencasRoute =
  AuthenticatedAdminLicencasRouteImport.update({
    id: '/licencas',
    path: '/licencas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmpresasRoute =
  AuthenticatedAdminEmpresasRouteImport.update({
    id: '/empresas',
    path: '/empresas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAprovacoesRoute =
  AuthenticatedAdminAprovacoesRouteImport.update({
    id: '/aprovacoes',
    path: '/aprovacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const CCompanySlugMTableSlugRoute = CCompanySlugMTableSlugRouteImport.update({
  id: '/m/$tableSlug',
  path: '/m/$tableSlug',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const AuthenticatedAdminEmpresasIdRoute =
  AuthenticatedAdminEmpresasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminEmpresasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/privacy': typeof PrivacyRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/payment': typeof AuthenticatedPaymentRoute
  '/c/$companySlug': typeof CCompanySlugRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/admin/aprovacoes': typeof AuthenticatedAdminAprovacoesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasRouteWithChildren
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/licencas': typeof AuthenticatedAdminLicencasRoute
  '/admin/metricas': typeof AuthenticatedAdminMetricasRoute
  '/app/atendimento': typeof AuthenticatedAppAtendimentoRoute
  '/app/catalogo': typeof AuthenticatedAppCatalogoRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/feed': typeof AuthenticatedAppFeedRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/inteligencia': typeof AuthenticatedAppInteligenciaRoute
  '/app/pedidos': typeof AuthenticatedAppPedidosRoute
  '/app/persona': typeof AuthenticatedAppPersonaRoute
  '/app/produtos': typeof AuthenticatedAppProdutosRoute
  '/c/$companySlug/checkout': typeof CCompanySlugCheckoutRoute
  '/c/$companySlug/confirmado': typeof CCompanySlugConfirmadoRoute
  '/c/$companySlug/desconexao': typeof CCompanySlugDesconexaoRoute
  '/c/$companySlug/feed': typeof CCompanySlugFeedRoute
  '/c/$companySlug/meus-pedidos': typeof CCompanySlugMeusPedidosRoute
  '/c/$companySlug/pagamento': typeof CCompanySlugPagamentoRoute
  '/c/$companySlug/perfil': typeof CCompanySlugPerfilRoute
  '/c/$companySlug/sacola': typeof CCompanySlugSacolaRoute
  '/c/$companySlug/vendas': typeof CCompanySlugVendasRoute
  '/oauth/mercadopago/callback': typeof OauthMercadopagoCallbackRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/c/$companySlug/': typeof CCompanySlugIndexRoute
  '/admin/empresas/$id': typeof AuthenticatedAdminEmpresasIdRoute
  '/c/$companySlug/m/$tableSlug': typeof CCompanySlugMTableSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/privacy': typeof PrivacyRoute
  '/termos': typeof TermosRoute
  '/payment': typeof AuthenticatedPaymentRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/aprovacoes': typeof AuthenticatedAdminAprovacoesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasRouteWithChildren
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/licencas': typeof AuthenticatedAdminLicencasRoute
  '/admin/metricas': typeof AuthenticatedAdminMetricasRoute
  '/app/atendimento': typeof AuthenticatedAppAtendimentoRoute
  '/app/catalogo': typeof AuthenticatedAppCatalogoRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/feed': typeof AuthenticatedAppFeedRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/inteligencia': typeof AuthenticatedAppInteligenciaRoute
  '/app/pedidos': typeof AuthenticatedAppPedidosRoute
  '/app/persona': typeof AuthenticatedAppPersonaRoute
  '/app/produtos': typeof AuthenticatedAppProdutosRoute
  '/c/$companySlug/checkout': typeof CCompanySlugCheckoutRoute
  '/c/$companySlug/confirmado': typeof CCompanySlugConfirmadoRoute
  '/c/$companySlug/desconexao': typeof CCompanySlugDesconexaoRoute
  '/c/$companySlug/feed': typeof CCompanySlugFeedRoute
  '/c/$companySlug/meus-pedidos': typeof CCompanySlugMeusPedidosRoute
  '/c/$companySlug/pagamento': typeof CCompanySlugPagamentoRoute
  '/c/$companySlug/perfil': typeof CCompanySlugPerfilRoute
  '/c/$companySlug/sacola': typeof CCompanySlugSacolaRoute
  '/c/$companySlug/vendas': typeof CCompanySlugVendasRoute
  '/oauth/mercadopago/callback': typeof OauthMercadopagoCallbackRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/c/$companySlug': typeof CCompanySlugIndexRoute
  '/admin/empresas/$id': typeof AuthenticatedAdminEmpresasIdRoute
  '/c/$companySlug/m/$tableSlug': typeof CCompanySlugMTableSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/privacy': typeof PrivacyRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/payment': typeof AuthenticatedPaymentRoute
  '/c/$companySlug': typeof CCompanySlugRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/_authenticated/admin/aprovacoes': typeof AuthenticatedAdminAprovacoesRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/empresas': typeof AuthenticatedAdminEmpresasRouteWithChildren
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/licencas': typeof AuthenticatedAdminLicencasRoute
  '/_authenticated/admin/metricas': typeof AuthenticatedAdminMetricasRoute
  '/_authenticated/app/atendimento': typeof AuthenticatedAppAtendimentoRoute
  '/_authenticated/app/catalogo': typeof AuthenticatedAppCatalogoRoute
  '/_authenticated/app/clientes': typeof AuthenticatedAppClientesRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/feed': typeof AuthenticatedAppFeedRoute
  '/_authenticated/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/_authenticated/app/inteligencia': typeof AuthenticatedAppInteligenciaRoute
  '/_authenticated/app/pedidos': typeof AuthenticatedAppPedidosRoute
  '/_authenticated/app/persona': typeof AuthenticatedAppPersonaRoute
  '/_authenticated/app/produtos': typeof AuthenticatedAppProdutosRoute
  '/c/$companySlug/checkout': typeof CCompanySlugCheckoutRoute
  '/c/$companySlug/confirmado': typeof CCompanySlugConfirmadoRoute
  '/c/$companySlug/desconexao': typeof CCompanySlugDesconexaoRoute
  '/c/$companySlug/feed': typeof CCompanySlugFeedRoute
  '/c/$companySlug/meus-pedidos': typeof CCompanySlugMeusPedidosRoute
  '/c/$companySlug/pagamento': typeof CCompanySlugPagamentoRoute
  '/c/$companySlug/perfil': typeof CCompanySlugPerfilRoute
  '/c/$companySlug/sacola': typeof CCompanySlugSacolaRoute
  '/c/$companySlug/vendas': typeof CCompanySlugVendasRoute
  '/oauth/mercadopago/callback': typeof OauthMercadopagoCallbackRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/c/$companySlug/': typeof CCompanySlugIndexRoute
  '/_authenticated/admin/empresas/$id': typeof AuthenticatedAdminEmpresasIdRoute
  '/c/$companySlug/m/$tableSlug': typeof CCompanySlugMTableSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/privacy'
    | '/termos'
    | '/admin'
    | '/app'
    | '/payment'
    | '/c/$companySlug'
    | '/p/$slug'
    | '/admin/aprovacoes'
    | '/admin/configuracoes'
    | '/admin/empresas'
    | '/admin/financeiro'
    | '/admin/licencas'
    | '/admin/metricas'
    | '/app/atendimento'
    | '/app/catalogo'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/feed'
    | '/app/financeiro'
    | '/app/inteligencia'
    | '/app/pedidos'
    | '/app/persona'
    | '/app/produtos'
    | '/c/$companySlug/checkout'
    | '/c/$companySlug/confirmado'
    | '/c/$companySlug/desconexao'
    | '/c/$companySlug/feed'
    | '/c/$companySlug/meus-pedidos'
    | '/c/$companySlug/pagamento'
    | '/c/$companySlug/perfil'
    | '/c/$companySlug/sacola'
    | '/c/$companySlug/vendas'
    | '/oauth/mercadopago/callback'
    | '/admin/'
    | '/app/'
    | '/c/$companySlug/'
    | '/admin/empresas/$id'
    | '/c/$companySlug/m/$tableSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/privacy'
    | '/termos'
    | '/payment'
    | '/p/$slug'
    | '/admin/aprovacoes'
    | '/admin/configuracoes'
    | '/admin/empresas'
    | '/admin/financeiro'
    | '/admin/licencas'
    | '/admin/metricas'
    | '/app/atendimento'
    | '/app/catalogo'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/feed'
    | '/app/financeiro'
    | '/app/inteligencia'
    | '/app/pedidos'
    | '/app/persona'
    | '/app/produtos'
    | '/c/$companySlug/checkout'
    | '/c/$companySlug/confirmado'
    | '/c/$companySlug/desconexao'
    | '/c/$companySlug/feed'
    | '/c/$companySlug/meus-pedidos'
    | '/c/$companySlug/pagamento'
    | '/c/$companySlug/perfil'
    | '/c/$companySlug/sacola'
    | '/c/$companySlug/vendas'
    | '/oauth/mercadopago/callback'
    | '/admin'
    | '/app'
    | '/c/$companySlug'
    | '/admin/empresas/$id'
    | '/c/$companySlug/m/$tableSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacidade'
    | '/privacy'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/payment'
    | '/c/$companySlug'
    | '/p/$slug'
    | '/_authenticated/admin/aprovacoes'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/empresas'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/licencas'
    | '/_authenticated/admin/metricas'
    | '/_authenticated/app/atendimento'
    | '/_authenticated/app/catalogo'
    | '/_authenticated/app/clientes'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/feed'
    | '/_authenticated/app/financeiro'
    | '/_authenticated/app/inteligencia'
    | '/_authenticated/app/pedidos'
    | '/_authenticated/app/persona'
    | '/_authenticated/app/produtos'
    | '/c/$companySlug/checkout'
    | '/c/$companySlug/confirmado'
    | '/c/$companySlug/desconexao'
    | '/c/$companySlug/feed'
    | '/c/$companySlug/meus-pedidos'
    | '/c/$companySlug/pagamento'
    | '/c/$companySlug/perfil'
    | '/c/$companySlug/sacola'
    | '/c/$companySlug/vendas'
    | '/oauth/mercadopago/callback'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/c/$companySlug/'
    | '/_authenticated/admin/empresas/$id'
    | '/c/$companySlug/m/$tableSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  PrivacyRoute: typeof PrivacyRoute
  TermosRoute: typeof TermosRoute
  CCompanySlugRoute: typeof CCompanySlugRouteWithChildren
  PSlugRoute: typeof PSlugRoute
  OauthMercadopagoCallbackRoute: typeof OauthMercadopagoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$companySlug': {
      id: '/c/$companySlug'
      path: '/c/$companySlug'
      fullPath: '/c/$companySlug'
      preLoaderRoute: typeof CCompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/payment': {
      id: '/_authenticated/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof AuthenticatedPaymentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/c/$companySlug/': {
      id: '/c/$companySlug/'
      path: '/'
      fullPath: '/c/$companySlug/'
      preLoaderRoute: typeof CCompanySlugIndexRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/oauth/mercadopago/callback': {
      id: '/oauth/mercadopago/callback'
      path: '/oauth/mercadopago/callback'
      fullPath: '/oauth/mercadopago/callback'
      preLoaderRoute: typeof OauthMercadopagoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$companySlug/vendas': {
      id: '/c/$companySlug/vendas'
      path: '/vendas'
      fullPath: '/c/$companySlug/vendas'
      preLoaderRoute: typeof CCompanySlugVendasRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/c/$companySlug/sacola': {
      id: '/c/$companySlug/sacola'
      path: '/sacola'
      fullPath: '/c/$companySlug/sacola'
      preLoaderRoute: typeof CCompanySlugSacolaRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/c/$companySlug/perfil': {
      id: '/c/$companySlug/perfil'
      path: '/perfil'
      fullPath: '/c/$companySlug/perfil'
      preLoaderRoute: typeof CCompanySlugPerfilRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/c/$companySlug/pagamento': {
      id: '/c/$companySlug/pagamento'
      path: '/pagamento'
      fullPath: '/c/$companySlug/pagamento'
      preLoaderRoute: typeof CCompanySlugPagamentoRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/c/$companySlug/meus-pedidos': {
      id: '/c/$companySlug/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/c/$companySlug/meus-pedidos'
      preLoaderRoute: typeof CCompanySlugMeusPedidosRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/c/$companySlug/feed': {
      id: '/c/$companySlug/feed'
      path: '/feed'
      fullPath: '/c/$companySlug/feed'
      preLoaderRoute: typeof CCompanySlugFeedRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/c/$companySlug/desconexao': {
      id: '/c/$companySlug/desconexao'
      path: '/desconexao'
      fullPath: '/c/$companySlug/desconexao'
      preLoaderRoute: typeof CCompanySlugDesconexaoRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/c/$companySlug/confirmado': {
      id: '/c/$companySlug/confirmado'
      path: '/confirmado'
      fullPath: '/c/$companySlug/confirmado'
      preLoaderRoute: typeof CCompanySlugConfirmadoRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/c/$companySlug/checkout': {
      id: '/c/$companySlug/checkout'
      path: '/checkout'
      fullPath: '/c/$companySlug/checkout'
      preLoaderRoute: typeof CCompanySlugCheckoutRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/_authenticated/app/produtos': {
      id: '/_authenticated/app/produtos'
      path: '/produtos'
      fullPath: '/app/produtos'
      preLoaderRoute: typeof AuthenticatedAppProdutosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/persona': {
      id: '/_authenticated/app/persona'
      path: '/persona'
      fullPath: '/app/persona'
      preLoaderRoute: typeof AuthenticatedAppPersonaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pedidos': {
      id: '/_authenticated/app/pedidos'
      path: '/pedidos'
      fullPath: '/app/pedidos'
      preLoaderRoute: typeof AuthenticatedAppPedidosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inteligencia': {
      id: '/_authenticated/app/inteligencia'
      path: '/inteligencia'
      fullPath: '/app/inteligencia'
      preLoaderRoute: typeof AuthenticatedAppInteligenciaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/financeiro': {
      id: '/_authenticated/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/feed': {
      id: '/_authenticated/app/feed'
      path: '/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof AuthenticatedAppFeedRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clientes': {
      id: '/_authenticated/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AuthenticatedAppClientesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/catalogo': {
      id: '/_authenticated/app/catalogo'
      path: '/catalogo'
      fullPath: '/app/catalogo'
      preLoaderRoute: typeof AuthenticatedAppCatalogoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/atendimento': {
      id: '/_authenticated/app/atendimento'
      path: '/atendimento'
      fullPath: '/app/atendimento'
      preLoaderRoute: typeof AuthenticatedAppAtendimentoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/metricas': {
      id: '/_authenticated/admin/metricas'
      path: '/metricas'
      fullPath: '/admin/metricas'
      preLoaderRoute: typeof AuthenticatedAdminMetricasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/licencas': {
      id: '/_authenticated/admin/licencas'
      path: '/licencas'
      fullPath: '/admin/licencas'
      preLoaderRoute: typeof AuthenticatedAdminLicencasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/empresas': {
      id: '/_authenticated/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AuthenticatedAdminEmpresasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/aprovacoes': {
      id: '/_authenticated/admin/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/admin/aprovacoes'
      preLoaderRoute: typeof AuthenticatedAdminAprovacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/c/$companySlug/m/$tableSlug': {
      id: '/c/$companySlug/m/$tableSlug'
      path: '/m/$tableSlug'
      fullPath: '/c/$companySlug/m/$tableSlug'
      preLoaderRoute: typeof CCompanySlugMTableSlugRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/_authenticated/admin/empresas/$id': {
      id: '/_authenticated/admin/empresas/$id'
      path: '/$id'
      fullPath: '/admin/empresas/$id'
      preLoaderRoute: typeof AuthenticatedAdminEmpresasIdRouteImport
      parentRoute: typeof AuthenticatedAdminEmpresasRoute
    }
  }
}

interface AuthenticatedAdminEmpresasRouteChildren {
  AuthenticatedAdminEmpresasIdRoute: typeof AuthenticatedAdminEmpresasIdRoute
}

const AuthenticatedAdminEmpresasRouteChildren: AuthenticatedAdminEmpresasRouteChildren =
  {
    AuthenticatedAdminEmpresasIdRoute: AuthenticatedAdminEmpresasIdRoute,
  }

const AuthenticatedAdminEmpresasRouteWithChildren =
  AuthenticatedAdminEmpresasRoute._addFileChildren(
    AuthenticatedAdminEmpresasRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAprovacoesRoute: typeof AuthenticatedAdminAprovacoesRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminEmpresasRoute: typeof AuthenticatedAdminEmpresasRouteWithChildren
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminLicencasRoute: typeof AuthenticatedAdminLicencasRoute
  AuthenticatedAdminMetricasRoute: typeof AuthenticatedAdminMetricasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAprovacoesRoute: AuthenticatedAdminAprovacoesRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminEmpresasRoute: AuthenticatedAdminEmpresasRouteWithChildren,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminLicencasRoute: AuthenticatedAdminLicencasRoute,
  AuthenticatedAdminMetricasRoute: AuthenticatedAdminMetricasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAtendimentoRoute: typeof AuthenticatedAppAtendimentoRoute
  AuthenticatedAppCatalogoRoute: typeof AuthenticatedAppCatalogoRoute
  AuthenticatedAppClientesRoute: typeof AuthenticatedAppClientesRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppFeedRoute: typeof AuthenticatedAppFeedRoute
  AuthenticatedAppFinanceiroRoute: typeof AuthenticatedAppFinanceiroRoute
  AuthenticatedAppInteligenciaRoute: typeof AuthenticatedAppInteligenciaRoute
  AuthenticatedAppPedidosRoute: typeof AuthenticatedAppPedidosRoute
  AuthenticatedAppPersonaRoute: typeof AuthenticatedAppPersonaRoute
  AuthenticatedAppProdutosRoute: typeof AuthenticatedAppProdutosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAtendimentoRoute: AuthenticatedAppAtendimentoRoute,
  AuthenticatedAppCatalogoRoute: AuthenticatedAppCatalogoRoute,
  AuthenticatedAppClientesRoute: AuthenticatedAppClientesRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppFeedRoute: AuthenticatedAppFeedRoute,
  AuthenticatedAppFinanceiroRoute: AuthenticatedAppFinanceiroRoute,
  AuthenticatedAppInteligenciaRoute: AuthenticatedAppInteligenciaRoute,
  AuthenticatedAppPedidosRoute: AuthenticatedAppPedidosRoute,
  AuthenticatedAppPersonaRoute: AuthenticatedAppPersonaRoute,
  AuthenticatedAppProdutosRoute: AuthenticatedAppProdutosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedPaymentRoute: typeof AuthenticatedPaymentRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedPaymentRoute: AuthenticatedPaymentRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CCompanySlugRouteChildren {
  CCompanySlugCheckoutRoute: typeof CCompanySlugCheckoutRoute
  CCompanySlugConfirmadoRoute: typeof CCompanySlugConfirmadoRoute
  CCompanySlugDesconexaoRoute: typeof CCompanySlugDesconexaoRoute
  CCompanySlugFeedRoute: typeof CCompanySlugFeedRoute
  CCompanySlugMeusPedidosRoute: typeof CCompanySlugMeusPedidosRoute
  CCompanySlugPagamentoRoute: typeof CCompanySlugPagamentoRoute
  CCompanySlugPerfilRoute: typeof CCompanySlugPerfilRoute
  CCompanySlugSacolaRoute: typeof CCompanySlugSacolaRoute
  CCompanySlugVendasRoute: typeof CCompanySlugVendasRoute
  CCompanySlugIndexRoute: typeof CCompanySlugIndexRoute
  CCompanySlugMTableSlugRoute: typeof CCompanySlugMTableSlugRoute
}

const CCompanySlugRouteChildren: CCompanySlugRouteChildren = {
  CCompanySlugCheckoutRoute: CCompanySlugCheckoutRoute,
  CCompanySlugConfirmadoRoute: CCompanySlugConfirmadoRoute,
  CCompanySlugDesconexaoRoute: CCompanySlugDesconexaoRoute,
  CCompanySlugFeedRoute: CCompanySlugFeedRoute,
  CCompanySlugMeusPedidosRoute: CCompanySlugMeusPedidosRoute,
  CCompanySlugPagamentoRoute: CCompanySlugPagamentoRoute,
  CCompanySlugPerfilRoute: CCompanySlugPerfilRoute,
  CCompanySlugSacolaRoute: CCompanySlugSacolaRoute,
  CCompanySlugVendasRoute: CCompanySlugVendasRoute,
  CCompanySlugIndexRoute: CCompanySlugIndexRoute,
  CCompanySlugMTableSlugRoute: CCompanySlugMTableSlugRoute,
}

const CCompanySlugRouteWithChildren = CCompanySlugRoute._addFileChildren(
  CCompanySlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  PrivacyRoute: PrivacyRoute,
  TermosRoute: TermosRoute,
  CCompanySlugRoute: CCompanySlugRouteWithChildren,
  PSlugRoute: PSlugRoute,
  OauthMercadopagoCallbackRoute: OauthMercadopagoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
