/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CCompanySlugRouteImport } from './routes/c.$companySlug'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as CCompanySlugIndexRouteImport } from './routes/c.$companySlug.index'
import { Route as CCompanySlugSacolaRouteImport } from './routes/c.$companySlug.sacola'
import { Route as CCompanySlugPublicarRouteImport } from './routes/c.$companySlug.publicar'
import { Route as CCompanySlugPerfilRouteImport } from './routes/c.$companySlug.perfil'
import { Route as CCompanySlugFeedRouteImport } from './routes/c.$companySlug.feed'
import { Route as CCompanySlugMTableSlugRouteImport } from './routes/c.$companySlug.m.$tableSlug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CCompanySlugRoute = CCompanySlugRouteImport.update({
  id: '/c/$companySlug',
  path: '/c/$companySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CCompanySlugIndexRoute = CCompanySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const CCompanySlugSacolaRoute = CCompanySlugSacolaRouteImport.update({
  id: '/sacola',
  path: '/sacola',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const CCompanySlugPublicarRoute = CCompanySlugPublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const CCompanySlugPerfilRoute = CCompanySlugPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const CCompanySlugFeedRoute = CCompanySlugFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const CCompanySlugMTableSlugRoute = CCompanySlugMTableSlugRouteImport.update({
  id: '/m/$tableSlug',
  path: '/m/$tableSlug',
  getParentRoute: () => CCompanySlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/c/$companySlug': typeof CCompanySlugRouteWithChildren
  '/c/$companySlug/feed': typeof CCompanySlugFeedRoute
  '/c/$companySlug/perfil': typeof CCompanySlugPerfilRoute
  '/c/$companySlug/publicar': typeof CCompanySlugPublicarRoute
  '/c/$companySlug/sacola': typeof CCompanySlugSacolaRoute
  '/c/$companySlug/': typeof CCompanySlugIndexRoute
  '/c/$companySlug/m/$tableSlug': typeof CCompanySlugMTableSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/c/$companySlug/feed': typeof CCompanySlugFeedRoute
  '/c/$companySlug/perfil': typeof CCompanySlugPerfilRoute
  '/c/$companySlug/publicar': typeof CCompanySlugPublicarRoute
  '/c/$companySlug/sacola': typeof CCompanySlugSacolaRoute
  '/c/$companySlug': typeof CCompanySlugIndexRoute
  '/c/$companySlug/m/$tableSlug': typeof CCompanySlugMTableSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/c/$companySlug': typeof CCompanySlugRouteWithChildren
  '/c/$companySlug/feed': typeof CCompanySlugFeedRoute
  '/c/$companySlug/perfil': typeof CCompanySlugPerfilRoute
  '/c/$companySlug/publicar': typeof CCompanySlugPublicarRoute
  '/c/$companySlug/sacola': typeof CCompanySlugSacolaRoute
  '/c/$companySlug/': typeof CCompanySlugIndexRoute
  '/c/$companySlug/m/$tableSlug': typeof CCompanySlugMTableSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/c/$companySlug'
    | '/c/$companySlug/feed'
    | '/c/$companySlug/perfil'
    | '/c/$companySlug/publicar'
    | '/c/$companySlug/sacola'
    | '/c/$companySlug/'
    | '/c/$companySlug/m/$tableSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/c/$companySlug/feed'
    | '/c/$companySlug/perfil'
    | '/c/$companySlug/publicar'
    | '/c/$companySlug/sacola'
    | '/c/$companySlug'
    | '/c/$companySlug/m/$tableSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/c/$companySlug'
    | '/c/$companySlug/feed'
    | '/c/$companySlug/perfil'
    | '/c/$companySlug/publicar'
    | '/c/$companySlug/sacola'
    | '/c/$companySlug/'
    | '/c/$companySlug/m/$tableSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  CCompanySlugRoute: typeof CCompanySlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$companySlug': {
      id: '/c/$companySlug'
      path: '/c/$companySlug'
      fullPath: '/c/$companySlug'
      preLoaderRoute: typeof CCompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/c/$companySlug/': {
      id: '/c/$companySlug/'
      path: '/'
      fullPath: '/c/$companySlug/'
      preLoaderRoute: typeof CCompanySlugIndexRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/c/$companySlug/sacola': {
      id: '/c/$companySlug/sacola'
      path: '/sacola'
      fullPath: '/c/$companySlug/sacola'
      preLoaderRoute: typeof CCompanySlugSacolaRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/c/$companySlug/publicar': {
      id: '/c/$companySlug/publicar'
      path: '/publicar'
      fullPath: '/c/$companySlug/publicar'
      preLoaderRoute: typeof CCompanySlugPublicarRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/c/$companySlug/perfil': {
      id: '/c/$companySlug/perfil'
      path: '/perfil'
      fullPath: '/c/$companySlug/perfil'
      preLoaderRoute: typeof CCompanySlugPerfilRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/c/$companySlug/feed': {
      id: '/c/$companySlug/feed'
      path: '/feed'
      fullPath: '/c/$companySlug/feed'
      preLoaderRoute: typeof CCompanySlugFeedRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/c/$companySlug/m/$tableSlug': {
      id: '/c/$companySlug/m/$tableSlug'
      path: '/m/$tableSlug'
      fullPath: '/c/$companySlug/m/$tableSlug'
      preLoaderRoute: typeof CCompanySlugMTableSlugRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CCompanySlugRouteChildren {
  CCompanySlugFeedRoute: typeof CCompanySlugFeedRoute
  CCompanySlugPerfilRoute: typeof CCompanySlugPerfilRoute
  CCompanySlugPublicarRoute: typeof CCompanySlugPublicarRoute
  CCompanySlugSacolaRoute: typeof CCompanySlugSacolaRoute
  CCompanySlugIndexRoute: typeof CCompanySlugIndexRoute
  CCompanySlugMTableSlugRoute: typeof CCompanySlugMTableSlugRoute
}

const CCompanySlugRouteChildren: CCompanySlugRouteChildren = {
  CCompanySlugFeedRoute: CCompanySlugFeedRoute,
  CCompanySlugPerfilRoute: CCompanySlugPerfilRoute,
  CCompanySlugPublicarRoute: CCompanySlugPublicarRoute,
  CCompanySlugSacolaRoute: CCompanySlugSacolaRoute,
  CCompanySlugIndexRoute: CCompanySlugIndexRoute,
  CCompanySlugMTableSlugRoute: CCompanySlugMTableSlugRoute,
}

const CCompanySlugRouteWithChildren = CCompanySlugRoute._addFileChildren(
  CCompanySlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  CCompanySlugRoute: CCompanySlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
