// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    headers.delete('Authorization');
    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function getSupabaseUrl(): string {
  const PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID || process.env.SUPABASE_PROJECT_ID;
  if (PROJECT_ID) return `https://${PROJECT_ID}.supabase.co`;

  const url = (import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL) as string | undefined;
  if (url && !url.includes('lovable.cloud')) return url;

  if (url?.includes('lovable.cloud')) {
    console.warn(
      `[Supabase] Detected Lovable proxy URL (${url}). POST requests will hang. ` +
      'Set VITE_SUPABASE_PROJECT_ID to use the direct Supabase URL.'
    );
  }

  throw new Error(
    'Could not determine Supabase URL. Set VITE_SUPABASE_PROJECT_ID or VITE_SUPABASE_URL in .env'
  );
}

function createSupabaseClient() {
  const SUPABASE_URL = getSupabaseUrl();
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_PUBLISHABLE_KEY) {
    throw new Error('Missing SUPABASE_PUBLISHABLE_KEY. Connect Supabase in Lovable Cloud.');
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

