// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

const SUPABASE_PROJECT_ID =
  import.meta.env.VITE_SUPABASE_PROJECT_ID || process.env.SUPABASE_PROJECT_ID;

const DIRECT_SUPABASE_URL = `https://${SUPABASE_PROJECT_ID}.supabase.co`;

function getSupabaseUrl(): string {
  const providedUrl = (import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL) as
    | string
    | undefined;

  // If the provided URL is already a direct Supabase URL (not proxy), use it
  if (providedUrl && !providedUrl.includes("lovable.cloud")) {
    return providedUrl;
  }

  // Warn if Lovable proxy is detected
  if (providedUrl?.includes("lovable.cloud") && !SUPABASE_PROJECT_ID) {
    console.warn(
      `[Supabase] Detected Lovable proxy URL (${providedUrl}). ` +
        "Using direct Supabase URL instead to avoid POST request issues.",
    );
  }

  if (!SUPABASE_PROJECT_ID) {
    throw new Error(
      "Missing SUPABASE_PROJECT_ID. Set VITE_SUPABASE_PROJECT_ID or SUPABASE_PROJECT_ID environment variable.",
    );
  }

  return DIRECT_SUPABASE_URL;
}

function createSupabaseClient() {
  const SUPABASE_URL = getSupabaseUrl();
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_PUBLISHABLE_KEY) {
    throw new Error("Missing SUPABASE_PUBLISHABLE_KEY. Connect Supabase in Lovable Cloud.");
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
